### ISSUE TITLE
Arduino Yun not sending hostname via DHCP on WAN and LAN

### ISSUE THREAD

**Issue by radames** [arduino/YunWebUI#19]
I've been trying to communicate two Arduinos Yun through their hostnames, however on my local wifi router their hostnames were unknown.

I realize that the `udhcpc` command was nothing using the option `-H` for setting the hostname.

After edit the file `/etc/config/network` and add the `option hostname 'myHostname'`

```

config interface 'lan'
        option hostname 'myHostname'
        option proto 'dhcp'

config interface 'wan'
        option hostname 'myHostname'
        option ifname 'eth1'
        option proto 'dhcp'
        option metric '10'
```

after restarting the network interface it started the `udhcpc` with the `-H` option

```
udhcpc -p /var/run/udhcpc-eth1.pid -s /lib/netifd/dhcp.script -f -t 0 -i eth1 -H myHostname -C
udhcpc -p /var/run/udhcpc-wlan0.pid -s /lib/netifd/dhcp.script -f -t 0 -i wlan0 -H myHostname -C
```

another issue was, I had to stop the `dnsmasq` process in order to Yun get the dnsnames from my wifi router.

Does anybody has a better workaround in how to automatize this using the Arduino Yun Name set from the web interface? Or is there any bug in the network interfaces setup?

**Comment by ffissore** [comment]
We haven't configured `/etc/config/network` that way because the yun uses avahi/zeroconf/bonjour for broadcasting its hostname on the network. Out of the box, you can ping your yun with `ping arduino.local`
Can you describe your use case and how the current setup limits your project?

**Comment by radames** [comment]
yes, I can ping the `arduino.local` outside the Arduino, however I was trying to communicate two Arduino Yun through their hostnames, i.e. setting up a `HttpClient.h`and using the `get("arduino.local\arduino\..." )`. This command uses the `curl` program and trying to `curl` from the command line via `ssh`, before my hacking, turns out `cannot resolve` the name.
I know I could use IP address in the to access the `HttpClient` clients, however I think as the boards has names, hostnames, why not access then through their hostname?

**Comment by ffissore** [comment]
I see your point. That's caused by lack of bonjour "client" support on the yun. Thanks for notifying. We'll fix it asap

**Comment by radames** [comment]
ok perfect! thanks
