### ISSUE TITLE
Lede and webpanel

### ISSUE THREAD

**Issue by ilovegalya** [arduino/YunWebUI#24]
Webpanel config doesn't work on latest LEDE

**Comment by facchinm** [comment]
Hi @ilovegalya ,
what do you mean with "doesn't work"?

**Comment by nxhack** [comment]
@facchinm @ilovegalya 

I also do not work well with LEDE - 17.01.
My situation is
Access http://arduino.local/, then redirect to http://ardunio.local/cgi-bin/luci/webpanel/homepage
I get
```
?:0: attempt to index a nil value
stack traceback:
	?: in function 'read_gpg_pub_key'
	?: in function 'authen'
	/usr/lib/lua/luci/dispatcher.lua:363: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>
```

Access http://arduino.local/cgi-bin/luci/
Luci's login screen appears. then login, Luci work fine.

**Comment by ilovegalya** [comment]
I’ve figured it out at some point and gone a little bit further. To fix show webpanel homepage I installed missed certificate or whatever it was and after that it was shown. But the functionality of webpanel is not full. I don’t care about stay alone webpanel. The most important thing for me is REST API. It doesn’t work. I thought I need turn off password for REST API using webpanel. Webpanel doesn’t provide ability to do it. I can only see interface with radio buttons that does nothing in my case

**Comment by nxhack** [comment]
Thank you @ilovegalya 

I found that key pair of arduino_gpg could not be generated by your comment.
It worked by fixing this.

**Comment by ilovegalya** [comment]
<img width="1280" alt="screen shot 2018-01-01 at 6 53 45 pm" src="https://user-images.githubusercontent.com/24204592/34468969-45468622-ef25-11e7-8a5e-3b5f208463fd.png">
<img width="1280" alt="screen shot 2018-01-01 at 6 54 04 pm" src="https://user-images.githubusercontent.com/24204592/34468970-45618ddc-ef25-11e7-919d-11a1626fd173.png">
I attached two screenshots. I have miscellaneous bugs in webpanel such as lost images and not working buttons. Second screenshot shows error which I got by trying to access to REST API. Had I been right that security option for the REST API comes the reason of that error? Does exist another way to configure this option?

**Comment by ilovegalya** [comment]
@nxhack Yeah I used gpg key to make webpanel accessable. But it's not the deal at all. It's just web pages without backend I guess

**Comment by nxhack** [comment]
@ilovegalya 
in "/etc/config/uhttpd
Does this description exist?
```
	list alias '/arduino=/cgi-bin/luci'
	list alias '/data=/cgi-bin/luci'
	list alias '/mailbox=/cgi-bin/luci'
```

**Comment by nxhack** [comment]
@ilovegalya 
There is a memo that I ported Arduino Yun's environment to LEDE. 

http://www.egrep.jp/wiki/index.php/OpenWrt_for_Arduino_Yun_cheat_sheet

**Comment by ilovegalya** [comment]
@nxhack Thank you very much for your attention. I solved all my problems by flashing this firmware [https://github.com/arduino/yun-go-updater/blob/master/tftp/ledeyun-17.11-r5461-ce9089c-ar71xx-generic-arduino-yun-squashfs-sysupgrade.bin](url) It works great
